name: receipt_checker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 今回のレシート解析のコアとなるAIパッケージ
  google_generative_ai: ^0.4.0
  # 画像の選択やカメラ撮影に使用
  image_picker: ^1.2.3

  intl: ^0.20.2
  shared_preferences: ^2.3.5
  path_provider: ^2.1.6
  table_calendar: ^3.1.2
  fl_chart: ^0.70.2
  cupertino_icons: ^1.0.8
  image: ^4.9.1

  # 旧プログラムで使っていた場合は残しておいて問題ありません
  google_mlkit_text_recognition: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true